{
    title: "ALSTAR Arena Sports Tournament",
        department: "ALSTAR G1",
            event_type: "Actual Event",
                date: "Monday-Wednesday, 13-15th April 2026",
                    image: "/images/events/upcoming/g1ae1.avif",
                        details_image: "/images/events/upcoming/g1ae2.avif",
                            instagram_link: "https://www.instagram.com/p/DWnr_FQEVqT/?img_index=1",
                                registration_link: "https://docs.google.com/forms/d/e/1FAIpQLSee-MjSlZAdJ4Cn4iHBtMk0WtqbJj1caYBcdk3Tz9cf7q6yzA/viewform?usp=dialog",
                                    trailer_link: "https://www.instagram.com/p/DWiABVNE3iM/"
},
{
    title: "Commanding the Capitol",
        department: "ALSTAR G2",
            event_type: "Actual Event",
                date: "Monday, 13th April 2026",
                    image: "/images/events/upcoming/g2ae1.avif",
                        details_image: "/images/events/upcoming/g2ae2.avif",
                            instagram_link: "https://www.instagram.com/p/DWOC7D7kblr/?img_index=1",
                                registration_link: "https://docs.google.com/forms/d/e/1FAIpQLSeCTDl1RF7P4K5_SdlU_GsZ6SPs467Ks_1-ozpVcQGVHo8-9A/viewform?usp=publish-editor ",
                                    trailer_link: "https://www.instagram.com/p/DWX6TwnkT7g/"
},
{
    title: "The Decision Lab",
        department: "ALSTAR G3",
            event_type: "Actual Event",
                date: "Monday, 13th April 2026 to Tuesday, 14th April 2026",
                    image: "/images/events/upcoming/g3ae1.avif",
                        details_image: "/images/events/upcoming/g3ae2.avif",
                            instagram_link: "https://www.instagram.com/p/DWOUHyoEa-z/?img_index=1",
                                registration_link: "https://forms.gle/r9JTNaQZGsKbTXdCA",
                                    trailer_link: "https://www.instagram.com/p/DWYnGdLkcsD/",
            },
{
    title: "House of Cards",
        department: "ALSTAR G5",
            event_type: "Actual Event",
                date: "Thursday, 9th April 2026",
                    image: "/images/events/upcoming/g5ae1.avif",
                        details_image: "/images/events/upcoming/g5ae2.avif",
                            instagram_link: "https://www.instagram.com/p/DWBm-uaESgJ/?img_index=1",
                                registration_link: "https://forms.gle/a3nC9BiSKmf3bJBJA",
                                    trailer_link: "https://www.instagram.com/p/DWlqD6FiSeS/",
            },
{
    title: "Friendship 101",
        department: "ALSTAR G7",
            event_type: "Actual Event",
                date: "Tuesday, 7th April 2026 to Thursday, 9th April 2026",
                    image: "/images/events/upcoming/g7ae1.avif",
                        details_image: "/images/events/upcoming/g7ae2.avif",
                            instagram_link: "https://www.instagram.com/p/DWTaOMkEe1A/?img_index=1",
                                registration_link: "https://forms.gle/BQwz9qhn9dmVJQiXA",
                                    trailer_link: "https://www.instagram.com/p/DWoAqkCEfbg/",
            },
{
    title: "Game On, Stress Gone",
        department: "ALSTAR G8",
            event_type: "Actual Event",
                date: "Wednesday, 15th April 2026",
                    image: "/images/events/upcoming/g8ae1.avif",
                        details_image: "/images/events/upcoming/g8ae2.avif",
                            instagram_link: "https://www.instagram.com/p/DWbMVmtETXz/?img_index=1",
                                registration_link: "https://docs.google.com/forms/d/e/1FAIpQLSc2TRHzljbwXLyXpjWky2NYIdBTIy7HOAi_N9j8TaXbPTg5mA/viewform?usp=dialog",
                                    trailer_link: "https://www.instagram.com/p/DWbNKB-EZRI/",
            },
{
    title: "Clash on Sunway",
        department: "ALSTAR G9",
            event_type: "Actual Event",
                date: "Wednesday, 15th April 2026 to Thursday, 16th April 2026",
                    image: "/images/events/upcoming/g9ae1.avif",
                        details_image: "/images/events/upcoming/g9ae2.avif",
                            instagram_link: "https://www.instagram.com/p/DV7-Ww4EdsL/?img_index=1",
                                registration_link: "https://docs.google.com/forms/d/e/1FAIpQLSfiRZ-pIp_OcAbAed-dMyHRSLzHZP9lG_scEKOgFVqT4gjzGA/viewform?usp=header",
                                    trailer_link: "https://www.instagram.com/p/DWN9H4lkWeG/",
            },
{
    title: "Dress to Impress",
        department: "ALSTAR G10",
            event_type: "Actual Event",
                date: "Wednesday, 15th April 2026 to Thursday, 16th April 2026",
                    image: "/images/events/upcoming/g10ae1.avif",
                        details_image: "/images/events/upcoming/g10ae2.avif",
                            instagram_link: "⁠https://www.instagram.com/p/DWgMFH1EVsu/?img_index=1&igsh=MTQ4YWZwZXVleWVhdw==",
                                registration_link: "⁠https://forms.gle/48zt8j3UM1XEs1wL8",
                                    trailer_link: "",
            },
{
    title: "Reclaiming The Future",
        department: "ALSTAR G11",
            event_type: "Actual Event",
                date: "Monday, 6th April 2026",
                    image: "/images/events/upcoming/g11ae1.avif",
                        details_image: "/images/events/upcoming/g11ae2.avif",
                            instagram_link: "https://www.instagram.com/p/DWTaSbEkRfN/?img_index=1",
                                registration_link: "https://forms.gle/yjzni855WPP8j7Kf7",
                                    trailer_link: "https://www.instagram.com/p/DWYkq_LkQsA/",
            },
{
    title: "A Gift of Learning",
        department: "ALSTAR G12",
            event_type: "Actual Event",
                date: "Friday, 17th April 2026",
                    image: "/images/events/upcoming/g12ae1.avif",
                        details_image: "/images/events/upcoming/g12ae2.avif",
                            instagram_link: "https://www.instagram.com/p/DWnXYTrEY8o/?igsh=aTlqcmh3MDl6bWZt",
                                registration_link: "https://docs.google.com/forms/d/e/1FAIpQLSe1BkLQDBg-6j2B0gzViv6qwNiV3XXjT9Gs5IHLyOFN3nJffA/viewform",
                                    trailer_link: "https://www.instagram.com/reel/DWp8LpvTaKQ/?igsh=MWRpanpmbXBncmRyZQ==",
            },